FROM ghcr.io/actions/actions-runner:2.320.0

USER root

# install zip
RUN apt-get update && apt-get install -y --no-install-recommends zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install azure cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

COPY github-actions-runner-azure-cli/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
