FROM ghcr.io/actions/actions-runner:2.319.1

USER root

# install curl, jq, zip and unzip
RUN apt-get update && apt-get install -y curl jq zip unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install azure cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

COPY github-actions-runner-azure-cli/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
